# Generated by Django 3.1.7 on 2021-03-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='imgae',
            field=models.ImageField(blank=True, null=True, upload_to='aboutus/'),
        ),
    ]
