# Generated by Django 3.1.7 on 2021-03-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20210313_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_us',
            old_name='imgae',
            new_name='image',
        ),
    ]
