# Generated by Django 3.1.7 on 2021-03-13 14:45

from django.db import migrations, models
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20210313_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=general.models.image_path),
        ),
    ]
