# Generated by Django 3.1.7 on 2021-03-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_sociallinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_desc', models.CharField(max_length=255)),
                ('address_title', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=400)),
            ],
        ),
    ]
