# Generated by Django 3.1.7 on 2021-03-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_company_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='copyright',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright', models.CharField(max_length=255)),
            ],
        ),
    ]
