# Generated by Django 3.1.7 on 2021-03-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
