# Generated by Django 3.1.7 on 2021-03-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='default event', max_length=255)),
                ('username', models.CharField(default='user', max_length=255)),
                ('phone', models.CharField(default='123456789', max_length=20)),
                ('email', models.CharField(blank=True, max_length=400, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=100)),
            ],
        ),
    ]
