# Generated by Django 3.1.7 on 2021-03-13 09:07

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
