# Generated by Django 3.1.7 on 2021-03-13 09:16

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0002_events_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='textcolor',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
