# Generated by Django 3.1.7 on 2021-03-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0002_auto_20210312_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogimage',
            old_name='post_id',
            new_name='post',
        ),
    ]
