# Generated by Django 3.1.7 on 2021-03-12 17:07

import admin_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_auto_20210312_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=admin_site.models.image_path),
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
    ]
